# Generated by Django 5.0.6 on 2024-06-03 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["id"],
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.AlterModelOptions(
            name="rate",
            options={
                "ordering": ["id"],
                "verbose_name": "Rate",
                "verbose_name_plural": "Rates",
            },
        ),
    ]
